---
version: '3'
services:
  backend:
    image: qnib/plain-influxdb:2.7.5
    environment:
     - INFLUXDB_BUCKET=metrics
     - INFLUXDB_META_LOGGING=true
    volumes:
     - /opt/influxdb/shared
    ports:
     - 2003:2003
     - 4242:4242
     - 8086:8086
  frontend:
    image: grafana/grafana-oss:10.2.3
    ports:
     - 3000:3000
    environment:
     - INFLUXDB_HOST=tasks.backend
     - INFLUXDB_DB=metrics
  telegraf:
    image: qnib/plain-telegraf:1.29.2-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - ENTRYPOINTS_DIR=/opt/entry
      - REMOTE_URL=http://backend:8086
      - DOCKER_SOCKET_URL=unix:///var/run/docker.sock
      - DOCKER_GATHER_SERVICES=true
  prometheus:
    image: qnib/plain-prometheus:2.48.1
    ports:
      - "9099:9090"
    environment:
      - PROM_REMOTE_WRITE_URL=http://telegraf:1234/receive
      - PROMETHEUS_STATIC_SCRAPE_LIST=prometheus:localhost:9090,cadvisor:cadvisor:8080
networks:
  hostnet:
    external:
      name: host
