---
version: 0.0.1
name: prometheus
description: "Monitoring stack with prometheus"
maintainers:
- name: Christian Kniep
  email: christian@qnib.org
targets:
  swarm: true
  kubernetes: true

---
version: '3'
services:
  backend:
    image: qnib/plain-influxdb:1.3.7@sha256:a8df362b7a951a8cc70850c2eb8a0cdd2876d29adbf74776580e4212c618c3f2
    environment:
     - INFLUXDB_DATABASES=metrics
     - INFLUXDB_META_LOGGING=true
    volumes:
     - /opt/influxdb/shared
    ports:
     - 2003:2003
     - 4242:4242
     - 8086:8086
  chronograf:
    image: qnib/plain-chronograf:0.1.3.7@sha256:23cf1696820dc8c2d3dbb9d11388c8465d68d9256dd38ab5a4f1a38adf579128
    ports:
     - 8888:8888
    environment:
     - INFLUXDB_HOST=tasks.backend
  frontend:
    image: qnib/plain-grafana4:4.6.2-7
    ports:
     - 3000:3000
    environment:
     - INFLUXDB_HOST=tasks.backend
     - INFLUXDB_DB=metrics
  cadvisor:
    image: google/cadvisor
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  node-exporter:
    image: quay.io/prometheus/node-exporter
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    pid: "host"
    networks: [hostnet]
  prometheus:
    image: qnib/plain-prometheus:2.0
    ports:
      - "9090:9090"
    environment:
        STORAGE_ADAPTER_HOST: tasks.prometheus-storage-adapter:9201
        PROMETHEUS_STATIC_SCRAPE_LIST: dockerd:172.17.0.1:9323:/metrics,node1:192.168.99.100:9100:/metrics,node2:192.168.99.101:9100:/metrics,node3:192.168.99.102:9100:/metrics
        PROMETHEUS_DNS_SCRAPE_LIST: cadvisor:tasks.cadvisor:8080:/metrics
  prometheus-storage-adapter:
    image: qnib/plain-prometheus-remote-storage
    environment:
      INFLUXDB_HOST: tasks.backend
      INFLUXDB_DB: metrics

networks:
  hostnet:
    external:
      name: host
