version: '3'
services:
  zookeeper:
    image: qnib/plain-zookeeper@sha256:6dfdaae24f3d1ef77e76dff85a5ab8ac7edb2d145935f213b7ae5176377eacc1
    ports:
      - "2181:2181"
  zkui:
    image: qnib/plain-zkui@sha256:9659927f707a97d6c6349bcda005520c9041d49f162a2124268368d88e289a19
    ports:
      - "9090:9090"
  broker:
    image: qnib/plain-kafka:1.0.0-1@sha256:c705a48932ac1f90e95afa0d6f4ab8ff68d8cd9fcec8bc4d0fa6b25747622dda
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    ports:
      - "9092:9092"
    deploy:
      replicas: 3
    environment:
      - KAFKA_BROKER_ID={{.Task.Slot}}
      - LOG_MESSAGE_FORMAT_VERSION=1.0-IV0
  manager:
    image: qnib/plain-kafka-manager:1.3.3.14@sha256:1582cfe5ecb60a52f3ebc137cabde628923f50b8bae22e8edd7121fc72ea740a
    ports:
      - "9000:9000"
    environment:
      ZOOKEEPER_HOSTS: "tasks.zookeeper:2181"

