version: '3'
services:
  master:
    image: qnib/plain-elasticsearch:5.5.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_HEAP_MAX: "512m"
      ES_HEAP_MIN: "512m"
      ES_NODE_MASTER: "true"
      ES_NODE_DATA: "true"
