version: '3.3'
services:
  server:
    image: qnib/alplain-gocd-server:18.1.0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
     - 8153:8153
     - 8154:8154
    secrets:
      - source: gocd_password_properties
        target: /etc/go/password.properties
        uid: '1000'
        gid: '1000'
        mode: 0440
    configs:
      - source: gocd_spack_config
        target: /opt/qnib/gocd/gocd-config.tar
        uid: '0'
        gid: '0'
        mode: 0400
    environment:
     - GOCD_SERVER_CLEAN_WORKSPACE=false
     - GOCD_AGENT_AUTOENABLE_KEY=qnibFTW
  agent:
    image: qnib/alplain-gocd-agent:18.1.0
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
    environment:
     - GO_SERVER_URL=https://tasks.server:8154/go
     - DOCKER_HOST=unix:///var/run/docker.sock
     - GOCD_AGENT_AUTOENABLE_KEY=qnibFTW
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

secrets:
  gocd_password_properties:
    file: ./gocd_password_properties
configs:
  gocd_spack_config:
    file: ./spack/gocd-config.tar
