version: '3'
services:
  master:
    image: qnib/plain-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_NODE_MASTER: "true"
      ES_NODE_DATA: "false"
  data:
    image: qnib/plain-elasticsearch
    deploy:
      replicas: 3
    environment:
      ES_NODE_MASTER: "false"
      ES_NODE_DATA: "true"
      ES_UNICAST_HOSTS: "tasks.master"
