version: '3'
services:
  prometheus:
    image: qnib/plain-prometheus:1.7.1-4@sha256:da042d1beda09728f8639aa33c41363e0bf83e6ca39f11e6d768417dd5c92c1c
    networks:
      - kafka_default
    ports:
      - "9091:9090"
    environment:
      PROMETHEUS_STATIC_SCRAPE_LIST: ""
      PROMETHEUS_DNS_SCRAPE_LIST: "kafka:tasks.broker:7071:/:1s,zookeeper:tasks.zookeeper:7071:/:1s"
      STORAGE_ADAPTER_HOST: "tasks.storage-adapter"
      STORAGE_ADAPTER_PORT: "9201"
  storage-adapter:
    image: qnib/plain-prometheus-remote-storage:aa5cdcb@sha256:4cb6929eb83c2f171b51877ea77765c9f6f31b081710ffa7e0c1230abf6b96e1
    networks:
      - kafka_default
  influxdb:
    image: qnib/plain-influxdb:1.3.5@sha256:fd65e66b559b3a9f367051212804bb1da9cf115b0fd93663bef4f522702bc5ab
    networks:
     - kafka_default
    environment:
     - INFLUXDB_DATABASES=prometheus
     - INFLUXDB_META_LOGGING=false
    volumes:
     - /opt/influxdb/shared
    ports:
     - 8083:8083
     - 8086:8086
  grafana:
    image: qnib/plain-grafana4:4.4.3-2@sha256:b84a409fa089a4c93b950d279e48ea9edddfb4265bf1fa8ce8b49e9f038a5a45
    networks:
      - kafka_default
    ports:
      - 3000:3000
    environment:
      - GRAFANA_DATA_SOURCES=prometheus,influxdb
      - INFLUXDB_HOST=tasks.influxdb
      - INFLUXDB_DB=prometheus

networks:
  kafka_default:
    external: true
