version: '3'
volumes:
  gitlabData:
  gitlabConfig:
  gitlabLogs:

services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - 'gitlabConfig:/etc/gitlab'
      - 'gitlabLogs:/var/log/gitlab'
      - 'gitlabData:/var/opt/gitlab'
