global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

#alertmanager_config:
#  dns_sd_configs:
#  - names:
#    - 'tasks.alertmanager'
#    type: 'A'
#    port: 9093

rule_files:
  - "swarm_node.rules"
  - "swarm_task.rules"
  - "swarm_service.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gpu-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.gpu-exporter'
      type: 'A'
      port: 9101

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
