version: '3'
services:
  broker:
    #commit d004a7c5c0c413e541e691b9ad99f2b9c7d8ae5a (HEAD -> master, origin/master, origin/HEAD)
    #Date:   Tue Sep 5 09:48:30 2017 +0200
    image: qnib/plain-kafka:0.11.0.0@sha256:50565ab8d0a396477aead338935373da8d319638cb3ea22f758d913970eb7caa
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    networks:
      - kafka_default
    ports:
      - "9092:9092"
    environment:
      SWARM_TASK_ID: '{{.Task.Slot}}'
      INTER_BROKER_PROTOCOL_VERSION: "0.11.0"
      LOG_MESSAGE_FORMAT_VERSION: "0.11.0"

networks:
  kafka_default:
    external: true
