version: '2'
services:
  consul: #1
    ports:
      - 8500:8500
    networks:
      - consul-net
    environment:
      - DC_NAME=swarm
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_SKIP_CURL=true
      # if more then one service is started, this is going to cause trouble
      - CONSUL_NODE_NAME=consul
    image: qnib/alpn-consul:d12
    volumes:
      - /etc/hostname:/etc/docker-hostname

networks:
  consul-net:
    driver: overlay
