version: '2'
services:
  consul: #1
    image: qnib/alpn-consul
    ports:
      - 8500:8500
    networks:
      - consul-net
    environment:
      - DC_NAME=swarm
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_SKIP_CURL=true
      # if more then one service is started, this is going to cause trouble
      - CONSUL_NODE_NAME=consul

networks:
  consul-net:
    driver: overlay
