version: '2'
services:
  gocd-server: #1
    image: qnib/gocd-server:d12
    networks:
     - consul-net
    ports:
     - 8153:8153
    environment:
     - DC_NAME=swarm
     - GOCD_SERVER_CLEAN_WORKSPACE=false
     - CONSUL_CLUSTER_IPS=consul
     # if more then one service is started, this is going to cause trouble
     - CONSUL_NODE_NAME=gocd-server
    labels:
      - "org.qnib.service.depend_on=consul"
    ### To persist your pipelines and backups, choose a path here. 
    ## !!! The path must exist, otherwise the service won't start
    #volumes:
    #  - /srv/go-server/serverBackups/:/opt/go-server/artifacts/serverBackups/
    #  - /srv/go-server/pipelines/:/srv/go-server/pipelines/

  gocd-agent: #global
    image: qnib/d12-alpn-gocd-agent
    networks:
     - consul-net
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "org.qnib.service.depend_on=consul,gocd-server"
    environment:
     - DC_NAME=swarm
     - GO_SERVER=gocd-server
     - GOCD_LOCAL_DOCKERENGINE=false
     - CONSUL_CLUSTER_IPS=consul

networks:
  consul-net:
    external: true
