apiVersion: v1
kind: Pod
metadata:
  name: trainer
  labels:
    app: trainer
spec:
  nodeSelector:
    houdini.gpu: "true"
  containers:
  - name: trainer
    image: qnib/uplain-webtest-houdini@sha256:0c463308c193f9eb400dda696b97b4fe63d4117018ac2f93ab214dffd392fa35
    env:
    - name: HOUDINI_GPU_REQUESTED
      value: "1"
    - name: WEBTEST_HTTP_PORT
      value: "9993"
    - name: CONTAINER_NAME
      value: "trainer"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
