apiVersion: v1
kind: Service
metadata:
  name: simulator
  labels:
    app: simulator
spec:
  ports:
  - port: 9991
    name: policy
  - port: 9992
    name: sim
  clusterIP: None
  selector:
    app: simulator
