version: '3'
services:
  zookeeper:
    image: qnib/plain-zookeeper@sha256:6dfdaae24f3d1ef77e76dff85a5ab8ac7edb2d145935f213b7ae5176377eacc1
    ports:
      - "2181:2181"
  broker:
    image: qnib/plain-kafka:0.10.2.1@sha256:c0cb9ad254228b2186b3d6607cce4df08c461e318111b3c114cf8e16105892df
    hostname: "{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}"
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: '{{.Task.Slot}}'
  manager:
    image: qnib/plain-kafka-manager:1.3.3.14@sha256:1582cfe5ecb60a52f3ebc137cabde628923f50b8bae22e8edd7121fc72ea740a
    ports:
      - "9000:9000"
    environment:
      ZOOKEEPER_HOSTS: "tasks.zookeeper:2181"
  qframe:
    image: qnib/qframe-ksql@sha256:b6564c8ef8d16b7ee5690985f9add746655cf8afe78b25c72a974973bf846b9b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  engine:
    image: qnib/plain-ksql@sha256:313df3edfc8d58f277921496e97d965a850d2096b36380283ce66a9c7a3b30bd
    environment:
      KAFKA_BROKERS: "tasks.broker:9092"
  kafkacat:
    image: qnib/plain-kafkacat
    command: tail -f /dev/null
