apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: policy
spec:
  selector:
    matchLabels:
      app: simulation # has to match .spec.template.metadata.labels
  serviceName: "simulation"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: simulation # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: policy
        image: qnib/plain-webtest-base:v0.2.1@sha256:ef36721536209f1d885d8ecf0e334ee835bf03c5bf8fba65f1fa6a9043dd3823
        ports:
        - containerPort: 9991
          name: policy
        env:
        - name: WEBTEST_HTTP_PORT
          value: "9991"
        - name: CONTAINER_NAME
          value: "policy"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: sim
        image: qnib/plain-webtest-base:v0.2.1@sha256:ef36721536209f1d885d8ecf0e334ee835bf03c5bf8fba65f1fa6a9043dd3823
        ports:
        - containerPort: 9992
          name: sim
        env:
        - name: WEBTEST_HTTP_PORT
          value: "9992"
        - name: CONTAINER_NAME
          value: "sim"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
