apiVersion: v1
kind: ReplicationController
metadata:
  name: simulator
spec:
  replicas: 3
  selector:
    app: simulator
  template:
    metadata:
      labels:
        app: simulator # has to match .spec.selector.matchLabels
    spec:
      nodeSelector:
        houdini.gpu: "true"
      containers:
      - name: policy
        image: qnib/uplain-webtest-houdini@sha256:0c463308c193f9eb400dda696b97b4fe63d4117018ac2f93ab214dffd392fa35
        ports:
        - containerPort: 9991
          name: policy
        env:
        - name: WEBTEST_HTTP_PORT
          value: "9991"
        - name: CONTAINER_NAME
          value: "policy"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      - name: sim
        image: qnib/uplain-webtest-houdini@sha256:0c463308c193f9eb400dda696b97b4fe63d4117018ac2f93ab214dffd392fa35
        ports:
        - containerPort: 9992
          name: sim
        env:
        - name: WEBTEST_HTTP_PORT
          value: "9992"
        - name: CONTAINER_NAME
          value: "sim"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
